"""Adding a has_acc column in user

Revision ID: 11a7006d75eb
Revises: da0cb447b67b
Create Date: 2023-09-15 17:47:20.238938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a7006d75eb'
down_revision = 'da0cb447b67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_acc', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_acc')

    # ### end Alembic commands ###
