"""Adding the account_pin clumnn

Revision ID: 159c06651b84
Revises: b9a47d76e208
Create Date: 2023-09-15 17:02:21.846741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159c06651b84'
down_revision = 'b9a47d76e208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_pin', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('account_pin')

    # ### end Alembic commands ###
