"""Changing a typoe

Revision ID: 184bbf266fa4
Revises: 5d01eee2f1cd
Create Date: 2023-09-14 13:19:45.139988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184bbf266fa4'
down_revision = '5d01eee2f1cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('acc_num',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('acc_num',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
