"""removing the account number column

Revision ID: 941621f81453
Revises: 875c91db6033
Create Date: 2023-09-14 13:26:13.580356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941621f81453'
down_revision = '875c91db6033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('acc_type')
        batch_op.drop_column('account_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_number', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('acc_type', sa.VARCHAR(length=240), nullable=True))

    # ### end Alembic commands ###
