"""adding a bank pin column

Revision ID: 9d472b37e5e2
Revises: baa3715f237d
Create Date: 2023-09-14 13:46:31.166988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d472b37e5e2'
down_revision = 'baa3715f237d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_pin', sa.String(length=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('account_pin')

    # ### end Alembic commands ###
