"""adding a constrain

Revision ID: baa3715f237d
Revises: 941621f81453
Create Date: 2023-09-14 13:30:38.270328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa3715f237d'
down_revision = '941621f81453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('account_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('bank_name',
               existing_type=sa.VARCHAR(length=240),
               nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('bank_name',
               existing_type=sa.VARCHAR(length=240),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('bank_name',
               existing_type=sa.VARCHAR(length=240),
               nullable=True)

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('bank_name',
               existing_type=sa.VARCHAR(length=240),
               nullable=True)
        batch_op.alter_column('account_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
