"""Adding the account_pin clumnn constraint

Revision ID: da0cb447b67b
Revises: 159c06651b84
Create Date: 2023-09-15 17:04:26.324627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0cb447b67b'
down_revision = '159c06651b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('account_pin',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.alter_column('account_pin',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)

    # ### end Alembic commands ###
